### ISSUE TITLE
`setindex()` order

### ISSUE THREAD

**Issue by andyferris** [eschnett/SIMD.jl#9]
Firstly, great package Erik! I think this is very cool. :+1: 

I was curious about `setindex(vec, index, value)` which defines things in a different order to `Base.setindex!(array, value, index)`. Was this intentional?

Also, is it likely to be "efficient" in the sense of does the generated code not make unnecessary copies? (Would it be a good way of implementing `map()`, say, or would all-at-once be better (obviously you lose the SIMD advantage when you apply an element-wise map, but some colleagues and I have been trying to use fast stack-allocated arrays for a while now, and they always seem tricky in Julia)).

**Comment by eschnett** [comment]
@andyferris Thanks! I'm always happy about feedback.

`setindex!` is not possible since these vectors are immutable tuples. Julia's regular tuples also don't have a `setindex!`. There's an `ntuple` function -- maybe SIMD should have a similar `nvec` function. Alternatively, we can define `setindex!` e.g. for `Ref{Vec{...}}`; that might be convenient in some cases, but will be much slower than expected due to the necessary heap allocation.

In general, it would be nice if the `v[i]=x` syntax could be lowered to `v = setindex(v,x,i)` for immutable types (including tuples). That is, however, a different discussion.

Yes, these vectors are likely to be efficient. I have studied the generated machine code, and it is highly efficient. In particular, even if you use `setindex`, the additional copies should be removed by the compiler, but I'm in general less certain about this. I prefer to use `vload` to load SIMD vectors from arrays; this is in general much more efficient.

If you refer to `setindex` -- no, this is unlikely to be efficient, as the vector needs to be disassembled and re-assembled. The whole point of SIMD vectors is that one accepts this cost, in exchange for more efficient whole-vector operations.

If you are looking for stack-allocated Julia arrays, then a package similar to SIMD that doesn't use SIMD vectors, but rather uses "LLVM arrays", would be more efficient.

**Comment by andyferris** [comment]
> setindex! is not possible since these vectors are immutable tuples.

@eschnett I understand - what I meant was - shouldn't `setindex` follow the same order of inputs as `setindex!`? I think it will be very confusing for users to write both and have to constantly reverse the order of value and index.

What I would like to write is:

    v2 = setindex(v1, 3, Val{2})

to set the second index to `3`.

**Comment by andyferris** [comment]
> In general, it would be nice if the v[i]=x syntax could be lowered to v = setindex(v,x,i) for immutable types (including tuples). That is, however, a different discussion.

Indeed. The Julia developers are very insistent to not entangle parsing with the type system, though.

> If you refer to setindex -- no, this is unlikely to be efficient, as the vector needs to be disassembled and re-assembled. The whole point of SIMD vectors is that one accepts this cost, in exchange for more efficient whole-vector operations.
> 
> If you are looking for stack-allocated Julia arrays, then a package similar to SIMD that doesn't use SIMD vectors, but rather uses "LLVM arrays", would be more efficient.

Right... we are already having this problem (unpacking and re-packing) with using tuples as fixed-size arrays (e.g. [FixedSizeArrays](https://github.com/simondanisch/FixedSizeArrays.jl), amongst other less-mature attempts), so I doubt that using `SIMD.jl` as a backend for something like that would be any slower. I'm curious about "LLVM arrays" but I know much less about LLVM than you. Would these be mutable but on the stack? How would Julia work with them? Anyway, it sounds cool.

One more question - if you have a 3-vector, will SIMD work for that? E.g. representing points in 3D space as `Float64` and subtract them. Would it be better/necessary to have a 4-vector with an extra zero to fill a 256-bit register, or will it figure it all out automatically?

**Comment by eschnett** [comment]
Changing the argument order for `setindex` should work. I didn't realize the order was inconsistent.

Julia uses LLVM arrays to represent tuples, so there would be no performance difference. They are stack allocated, but immutable -- the way to make them "mutable" is the `v = setindex(v, x, i)` trick. With parser support, it wouldn't look bad. Of course, for large arrays (>10 elements), the compiler would need to work very hard to eliminate all unnecessary copies. From a user point of view, these would look like a tuple that has more operations defined.

Yes, length 3 SIMD vectors work fine. Internally, LLVM will use the most efficient representation, which could be either a 4-vector with one unused element, or a combination of a 2-vector and a scalar. This depends on the CPU you are using. However, LLVM currently has a bug, and certain "uneven" sizes don't work; length 7 is the smallest one that currently doesn't work on Intel CPUs.

**Comment by andyferris** [comment]
OK, thanks for the feedback. My small look at LLVM seemed to indicate you could get pointers to your stack-allocated LLVM-Arrays, like in C, so I figured with the right LLVM call we could mutate them (not sure what assumptions are made on the Julia side when doing this!).

If we are talking about tuples, this might include mixed-data-length tuples, like `Tuple{Int32, Float64, Bool}`. Do you mean Julia uses a different LLVM representation especially for `NTuples` of certain data types, or something?

**Comment by andyferris** [comment]
Oh, and are there any thoughts on a matrix type, say `Mat{N,M,T}`, which could multiply `Vec{M,T}` to give a `Vec{N,T}` or something? Or would you consider that outside the scope of the package?
